version: "3.8"
services:
  chatterloop-worker-service:
    image: johnpauloramil187/chatterloop_worker_service:${IMAGE_TAG:-latest}
    secrets:
      - source: chatterloop-worker-service_env
        target: /app/.env
      - source: astra_bundle
        target: /app/secure-connect-chatterloop.zip
    environment:
      - APP_VERSION=${IMAGE_TAG:-latest}
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.routers.chatterloopworkerservice.rule=Host(`worker.chatterloop.app`)"
        - "traefik.http.routers.chatterloopworkerservice.entrypoints=websecure"
        - "traefik.http.routers.chatterloopworkerservice.tls.certresolver=letsencrypt"
        - "traefik.http.services.chatterloopworkerservice.loadbalancer.server.port=8880"
        - "traefik.docker.network=traefik-public"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
    name: traefik-public

secrets:
  chatterloop-worker-service_env:
    external: true
  astra_bundle:
    external: true
