version: "3.8"
services:
  neon-centralized-api:
    image: johnpauloramil187/neon_centralized_api:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.routers.neoncentralizedapi.rule=Host(`api.neonsystems.net`)"
        - "traefik.http.routers.neoncentralizedapi.entrypoints=websecure"
        - "traefik.http.routers.neoncentralizedapi.tls.certresolver=letsencrypt"
        - "traefik.http.services.neoncentralizedapi.loadbalancer.server.port=8004"
        - "traefik.docker.network=traefik-public"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
    name: traefik-public
