version: "3.8"
services:
  neon-remote:
    image: johnpauloramil187/neonremote-ui:latest
    secrets:
      - source: neon-remote_env
        target: /app/.env
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.routers.neonremote.rule=Host(`remote.neonsystems.net`)"
        - "traefik.http.routers.neonremote.entrypoints=websecure"
        - "traefik.http.routers.neonremote.tls.certresolver=letsencrypt"
        - "traefik.http.services.neonremote.loadbalancer.server.port=3006"
        - "traefik.docker.network=traefik-public"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
    name: traefik-public

secrets:
  neon-remote_env:
    external: true
